name: CI

on:
  push:
    branches:
      - "main"
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: "24.2.2"
          gleam-version: "0.27.0"
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.18.1"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: gleam test --target erlang
      - run: gleam test --target javascript
      - run: deno test
      - run: gleam format --check src test
